// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfig(arg1) {
  return window['go']['main']['App']['ApplyConfig'](arg1);
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetDBConnectionsList() {
  return window['go']['main']['App']['GetDBConnectionsList']();
}

export function GetLogHistory() {
  return window['go']['main']['App']['GetLogHistory']();
}

export function GetScadaStatus() {
  return window['go']['main']['App']['GetScadaStatus']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ReconnectDB(arg1) {
  return window['go']['main']['App']['ReconnectDB'](arg1);
}

export function RefreshScadaToken() {
  return window['go']['main']['App']['RefreshScadaToken']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}
