// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';
import {logger} from '../models';
import {scada} from '../models';

export function ApplyConfig(arg1:main.AppConfig):Promise<void>;

export function GetAutoStart():Promise<boolean>;

export function GetConfigPath():Promise<string>;

export function GetDBConnectionsList():Promise<Array<db.ConnStatus>>;

export function GetLogHistory():Promise<Array<logger.Entry>>;

export function GetScadaStatus():Promise<scada.ConnectionStatus>;

export function LoadConfig():Promise<main.AppConfig>;

export function ReconnectDB(arg1:string):Promise<void>;

export function RefreshScadaToken():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;
